/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.github.dmmn_games.earth_2045.gui;

import io.github.dmmn_games.earth_2045.user.User;
import io.github.dmmn_games.earth_2045.commands.*;
import io.github.dmmn_games.earth_2045.game.GameController;
import java.awt.event.KeyEvent;

/**
 *
 * @author iordkost
 */
public class Game extends javax.swing.JFrame {

    private UIConfig UIConfig;
    private GameController GameController;
    private CommandsController CommandsController;
    
    /**
     * Creates new form Game
     */
    public Game() {
        initGame();
        this.GameController = new GameController();        
    }
    
    public Game(String argUser) {
        initGame();
        this.GameController = new GameController();
        
        // ToDo : Set Username
        System.err.print(argUser);
        
    }
    
    public Game(GameController LoadedGame) {
        initGame();
        this.GameController = LoadedGame;
    }
    
    private void initGame() {
        // Init Components
        initComponents();
        
        // Apply UI Settings
        UIConfig = new UIConfig();
        UIConfig.initUI(this);
        
        // Init Commands Controller
        CommandsController = new CommandsController();
        
        // Init History Logger
        initHistory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanel = new javax.swing.JScrollPane();
        commandHistory = new javax.swing.JTextArea();
        submitCommand = new javax.swing.JButton();
        currentCommand = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        commandHistory.setEditable(false);
        commandHistory.setColumns(20);
        commandHistory.setRows(5);
        scrollPanel.setViewportView(commandHistory);

        submitCommand.setText("Submit");
        submitCommand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitCommandMouseClicked(evt);
            }
        });

        currentCommand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                currentCommandKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(currentCommand)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(submitCommand)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitCommand)
                    .addComponent(currentCommand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initHistory() {
        commandHistory.setText("Ready...." + "\n");
    }
    
    private void execCommand() {
        CommandsController.runCommand(currentCommand, commandHistory, GameController);
    }
    
    private void submitCommandMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitCommandMouseClicked
        execCommand();
    }//GEN-LAST:event_submitCommandMouseClicked

    private void currentCommandKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_currentCommandKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            execCommand();
        }
    }//GEN-LAST:event_currentCommandKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea commandHistory;
    private javax.swing.JTextField currentCommand;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JButton submitCommand;
    // End of variables declaration//GEN-END:variables
}
