package io.github.dmmn_games.earth_2045.forms;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author elgreko
 */
import io.github.dmmn_games.earth_2045.user.User;
import io.github.dmmn_games.earth_2045.npcs.Bot;
import io.github.dmmn_games.earth_2045.user.User;
import java.util.logging.Level;
import java.util.logging.Logger;


public class BotConversation extends javax.swing.JFrame
{
    
    String previousHistory;
    String History;
    Bot currentBot;
    User currentUser;
    private UIConfig uiConfig;
    

    /**
     * Creates new form Frame
     */
    public BotConversation()
    {
        
        
        initComponents();
        
    }

    public BotConversation(User currentUser, String currentBot)
    {
        initComponents();
        this.currentUser = currentUser;
        try
        {
            this.currentBot = currentUser.findBot(currentBot) ;
        } catch (Exception ex)
        {
            System.err.println(ex.getMessage());
        }
        
        // Apply UI Settings
        uiConfig = new UIConfig();

        try {
            uiConfig.initUI(this);
        } catch (Exception ex) {
            System.err.println(ex.getMessage());
        }
        
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        talkButton = new javax.swing.JButton();
        userText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        conversation = new javax.swing.JTextArea();
        exitButton = new javax.swing.JButton();
        labelName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        talkButton.setText("Talk");
        talkButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                talkButtonActionPerformed(evt);
            }
        });

        userText.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                userTextActionPerformed(evt);
            }
        });

        conversation.setColumns(20);
        conversation.setRows(5);
        jScrollPane1.setViewportView(conversation);

        exitButton.setText("EXIT CONVERSATION");
        exitButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                exitButtonActionPerformed(evt);
            }
        });

        labelName.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelName.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                    .addComponent(exitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(userText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(talkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(talkButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    
    
    private void talkButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_talkButtonActionPerformed
    {//GEN-HEADEREND:event_talkButtonActionPerformed
        History = userText.getText();        
        conversation.append(currentUser.getUsername()+ ": " + History + "\n\n");        
        userText.setText(""); 
        String botAnswer = currentBot.talk(History);
        conversation.append(currentBot.getName()+ ": " + botAnswer + "\n\n");
        



        //String botTalk = currentBot.talk(History, currentUser.getUsername());
        //conversation.append(currentBot.getName()+ ": " +botTalk);
        /*if(botTalk.equals(currentBot.botQuestion[3])){
            enableExitButton();
        }*/
            
        userText.requestFocus();
        
    }//GEN-LAST:event_talkButtonActionPerformed

    private void userTextActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_userTextActionPerformed
    {//GEN-HEADEREND:event_userTextActionPerformed
        
        History = userText.getText();        
        conversation.append(currentUser.getUsername()+ ": " + History + "\n\n");        
        userText.setText(""); 
        String botAnswer = currentBot.talk(History);
        conversation.append(currentBot.getName()+ ": " + botAnswer + "\n\n");
        
        if(botAnswer.matches(currentBot.getSuccesAnswer())){
            enableExitButton();
        }
           
        
        


        //String botTalk = currentBot.talk(History, currentUser.getUsername());
        //conversation.append(currentBot.getName()+ ": " +botTalk);
        /*if(botTalk.matches(currentBot.botQuestion[2])){
            enableExitButton();
        }*/
            
        userText.requestFocus();
            
       
               
    }//GEN-LAST:event_userTextActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        exitButton.setVisible(false);
        userText.requestFocus();
        conversation.append(currentBot.getName() + ": " + currentBot.getQuestion());
        currentBot.setFlowCheck(0);
        labelName.setText(currentBot.getName());
        
    }//GEN-LAST:event_formWindowOpened

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_exitButtonActionPerformed
    {//GEN-HEADEREND:event_exitButtonActionPerformed
        this.dispose();        // TODO check if there's a better way to close form.
    }//GEN-LAST:event_exitButtonActionPerformed
    
    
    
    
    
    
    
    
    
    public void enableExitButton(){
        
        userText.setVisible(false);
        talkButton.setVisible(false);
        exitButton.setVisible(true);
        exitButton.requestFocus();
        
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(BotConversation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(BotConversation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(BotConversation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(BotConversation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new BotConversation().setVisible(true);
                
            }
        });
        
        
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea conversation;
    private javax.swing.JButton exitButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelName;
    private javax.swing.JButton talkButton;
    private javax.swing.JTextField userText;
    // End of variables declaration//GEN-END:variables
}
