/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.github.dmmn_games.earth_2045.forms;

import com.google.gson.Gson;
import io.github.dmmn_games.earth_2045.game.CommandUI;
import io.github.dmmn_games.earth_2045.game.GameController;
import io.github.dmmn_games.earth_2045.music.Music;
import io.github.dmmn_games.earth_2045.saveload.Save;
import java.awt.event.KeyEvent;
import java.net.MalformedURLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Timer;
import javax.swing.JFrame;

/**
 *
 * @author iordkost
 */
public class Game extends JFrame {

    private final GameController gameControler;

    private UIConfig uiConfig;
    private Music music;
    private List<String> commandHistory;
    private int historyIndex;
    private String currentSlot;

    private TimeLimiter timeLimiter;
    private Timer gameLimiter;

    /**
     * Creates new form Game
     */
    public Game() {
        initGame();
        gameControler = new GameController();

    }

    public Game(String username, int time, String saveSlot) {
        initGame();

        gameControler = new GameController();
        gameControler.initWorld(username, time);

        currentSlot = saveSlot;

        timeLimiter = new TimeLimiter(
                secsRemLabelReal,
                time,
                currentCommand,
                submitCommand,
                gameControler
        );
        gameLimiter = new Timer(1000, timeLimiter);
        gameLimiter.start();

        currentCommand.setText("man story");
        execCommand();

    }

    public Game(GameController loadedGame, String loadedSlot) {
        initGame();

        gameControler = loadedGame;
        currentSlot = loadedSlot;

        timeLimiter = new TimeLimiter(
                secsRemLabelReal,
                loadedGame.getTime(),
                currentCommand,
                submitCommand, gameControler
        );
        gameLimiter = new Timer(1000, timeLimiter);
        gameLimiter.start();
    }

    private void initGame() {

        // Init Components
        initComponents();

        // Apply UI Settings
        uiConfig = new UIConfig();

        try {
            uiConfig.initUI(this);
        } catch (Exception ex) {
            System.err.println(ex.getMessage());
        }

        // Init CommandUI Logger
        initHistory();

        // Play Music
        music = new Music();
        music.Play();

        // Init Command History
        this.commandHistory = new ArrayList<>();
        this.historyIndex = 0;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanel = new javax.swing.JScrollPane();
        commandLogger = new javax.swing.JTextArea();
        submitCommand = new javax.swing.JButton();
        currentCommand = new javax.swing.JTextField();
        secsRemLabel = new javax.swing.JLabel();
        secsRemLabelReal = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        commandLogger.setEditable(false);
        commandLogger.setColumns(20);
        commandLogger.setLineWrap(true);
        commandLogger.setRows(5);
        scrollPanel.setViewportView(commandLogger);

        submitCommand.setText("Submit");
        submitCommand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitCommandMouseClicked(evt);
            }
        });

        currentCommand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                currentCommandKeyPressed(evt);
            }
        });

        secsRemLabel.setText("Time Remaining");

        secsRemLabelReal.setText("00:00");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPanel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(currentCommand, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(submitCommand))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(secsRemLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(secsRemLabelReal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secsRemLabel)
                    .addComponent(secsRemLabelReal)
                    .addComponent(saveButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitCommand)
                    .addComponent(currentCommand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initHistory() {
        commandLogger.setText("Ready...." + "\n");

    }

    private void execCommand() {

        commandHistory.add(currentCommand.getText());
        historyIndex = commandHistory.size() - 1;

        String Response = gameControler.getCommandsController().runCommand(
                currentCommand.getText(),
                gameControler
        );

        if (Response.equals("CLEAR")) {
            commandLogger.setText("");
        } else if (Response.contains("TALK")) {
            BotConversation botConversation = new BotConversation(
                    gameControler.getUser(),
                    Response.substring(4)
            );
        } else {
            new CommandUI(commandLogger).addLine(Response);

        }
        currentCommand.setText("");

    }

    private void submitCommandMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitCommandMouseClicked
        execCommand();
    }//GEN-LAST:event_submitCommandMouseClicked

    private void currentCommandKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_currentCommandKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                execCommand();
                break;
            case KeyEvent.VK_UP:
                currentCommand.setText(commandHistory.get(historyIndex));
                if (historyIndex == 0) {
                    historyIndex = commandHistory.size() - 1;
                } else {
                    historyIndex--;
                }
                break;
            case KeyEvent.VK_DOWN:
                currentCommand.setText(commandHistory.get(historyIndex));
                if (historyIndex < commandHistory.size() - 1) {
                    historyIndex++;
                } else {
                    historyIndex = 0;
                }
                break;
            default:
                break;
        }
    }//GEN-LAST:event_currentCommandKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        currentCommand.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        gameControler.setTime(timeLimiter.getSeconds());
        new Save().run(currentSlot, gameControler);
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Game().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea commandLogger;
    private javax.swing.JTextField currentCommand;
    private javax.swing.JButton saveButton;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JLabel secsRemLabel;
    private javax.swing.JLabel secsRemLabelReal;
    private javax.swing.JButton submitCommand;
    // End of variables declaration//GEN-END:variables
}
