/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.github.dmmn_games.earth_2045.forms;

import io.github.dmmn_games.earth_2045.commands.Load;
import io.github.dmmn_games.earth_2045.game.GameController;
import java.awt.event.KeyEvent;
import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author iordkost
 */
public class LoadGame extends javax.swing.JFrame {

    private UIConfig UIConfig;
    private GameController[] Slots;
    /**
     * Creates new form LoadGame
     */
    public LoadGame() {
        initComponents();
        
        // Apply UI Settings
        UIConfig = new UIConfig();
        try {
            UIConfig.initUI(this);
        } catch (MalformedURLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Slots = new GameController[3];
        
        Slots[0] = new Load().loadProcess("a");
        Slots[1] = new Load().loadProcess("b");
        Slots[2] = new Load().loadProcess("c");
        
        
        String[] loadListItems = new String[3];
        
        for(int i=0;i<loadListItems.length;i++) {
            if(Slots[i].getUser().getUsername() == "Empty") {
                loadListItems[i] = "Empty Slot";
            } else {
                loadListItems[i] = "Username: " + Slots[i].getUser().getUsername() + " ";
                loadListItems[i] += "Floor: " + Slots[i].getUser().getFloor() + " ";
                loadListItems[i] += "Room: " + Slots[i].getUser().getRoom();
            }
        }
        
        loadList.setListData(loadListItems);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        loadList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loadList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadListMouseClicked(evt);
            }
        });
        loadList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loadListKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(loadList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadListMouseClicked
        if(Slots[loadList.getSelectedIndex()].getUser().getUsername() == "Empty") {
            //
        } else {
            Game loadGame = new Game(Slots[loadList.getSelectedIndex()]);
            loadGame.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_loadListMouseClicked

    private void loadListKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loadListKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            loadListMouseClicked(null);
        }
    }//GEN-LAST:event_loadListKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoadGame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> loadList;
    // End of variables declaration//GEN-END:variables
}
